services:
  rollup_node:
    build:
      context: .
      dockerfile: Dockerfile.multi
    environment:
      - SERVICE=rollup_node  # Set this explicitly for rollup_node
    entrypoint: ["/app/bin/rollup_node"]  # Override the ENTRYPOINT
  mock_client:
    build:
      context: .
      dockerfile: Dockerfile.multi
    environment:
      - SERVICE=mock_client
    entrypoint: ["/app/bin/mock_client"]  # Override the ENTRYPOINT
  batcher:
    build:
      context: .
      dockerfile: Dockerfile.multi
    environment:
      - SERVICE=batcher
    entrypoint: ["/app/bin/batcher"]  # Override the ENTRYPOINT
